<a href="https://colab.research.google.com/github/jasurbektoshpolatov/M-Firs-Project-Json/blob/master/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 1.Import the numpy package under the name np (★☆☆)
import numpy as np

In [ ]:
# 2.Print the numpy version and the configuration (★☆☆)
np.__version__

'1.21.6'

In [ ]:
# 3. Create a zero vector of size 10 (★☆☆)
a = np.unique([1, 1, 2, 2, 3, 4, 4, 5, 5])
a

array([1, 2, 3, 4, 5])

In [ ]:
# 4. How to find the memory size of any array (★☆☆)
a = np.zeros(10)
a.size * a.itemsize

80

In [ ]:
# 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x7f5bc4dc7410>, toplevel='numpy')>

In [ ]:
# 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
# 7. Create a vector with values ranging from 10 to 49 (★☆☆)
# 8. Reverse a vector (first element becomes last) (★☆☆)
a = np.arange(10, 49)
print(a)
a = a[::-1]
print(f"\n{a}") # To show you i have printed with format method!

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
a = np.mat([[1, 2, 3], [4, 5, 6], [4, 2, 6]])
a.reshape(3, 3)

matrix([[1, 2, 3],
        [4, 5, 6],
        [4, 2, 6]])

In [ ]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
a = np.nonzero([1,2,0,0,4,0])   # nonzero method find with index numbers which does'nt have zero numbers
a

(array([0, 1, 4]),)

In [ ]:
# 11. Create a 3x3 identity matrix (★☆☆)
a = np.identity(3)  
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 12. Create a 3x3x3 array with random values (★☆☆)
a = np.random.random((3, 3, 3))
print(a)
a = np.random.randint(27, size=(3, 3, 3))
print(f"\n{a}")

[[[0.62933996 0.80129434 0.24251073]
  [0.51681031 0.86461665 0.40261836]
  [0.9640692  0.00448657 0.5529326 ]]

 [[0.21379328 0.33289279 0.29033502]
  [0.9223267  0.65755206 0.31438207]
  [0.69673608 0.8057002  0.68956973]]

 [[0.901779   0.24692168 0.6378512 ]
  [0.02895751 0.43851086 0.3510659 ]
  [0.6580084  0.05025064 0.52598212]]]

[[[26 14 17]
  [25 13 26]
  [19 21 21]]

 [[11 25 21]
  [11 17 26]
  [12  9 26]]

 [[26  8 20]
  [22 12  0]
  [16  6 14]]]


In [ ]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
a = np.random.random((10, 10))
print(a.min())
print(f"\n{a.max()}")

0.056949658198722775

0.9987905496038312


In [ ]:
# 14. Create a random vector of size 30 and find the mean value (★☆☆)
a = np.random.random(30)
a.mean()

0.602242013459389

In [ ]:
# 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
a = np.ones((5, 5))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
a = [326, 327, 328, 329, 330]
np.pad(a, (3, 3), "reflect", reflect_type = "odd") # maximum, minimum, symmetric, # symmetric_type = "odd" median, reflect # reflect_type = "odd", wrap


array([323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333])

In [ ]:
# 17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [ ]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
a = np.mat([[1, 2, 3, 4, 1], [1, 2, 3, 4, 1], [1, 2, 3, 4, 1], [1, 2, 3, 4, 1], [1, 2, 3, 4, 1]])
b = np.diag(a)
b

array([1, 2, 3, 4, 1])

In [ ]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
a = np.mat([[2, 3, 4, 5, 6, 4, 2, 4], [4, 5, 3, 6, 2, 3, 1, 7], [3, 9, 8, 4, 7, 5, 2, 8], [7, 3, 4, 5, 2, 9, 2, 6], [2, 3, 4, 6, 5, 2, 5, 6], [8, 7, 4, 9, 3, 6, 3, 2], [2, 3, 8, 9, 4, 5, 7, 9], [8, 5, 2, 3, 9, 2, 7, 3]])
b = np.array(a[::2])
b

array([[2, 3, 4, 5, 6, 4, 2, 4],
       [3, 9, 8, 4, 7, 5, 2, 8],
       [2, 3, 4, 6, 5, 2, 5, 6],
       [2, 3, 8, 9, 4, 5, 7, 9]])

In [ ]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
a = np.unravel_index(100, (6, 7, 8))
a

(1, 5, 4)

In [ ]:
# 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
a = np.mat([[2, 3, 4, 5, 6], [4, 5, 3, 6, 2], [3, 9, 8, 4, 7], [7, 3, 4, 5, 2], [2, 3, 4, 6, 5]])
np.tile(a, 2)

matrix([[2, 3, 4, 5, 6, 2, 3, 4, 5, 6],
        [4, 5, 3, 6, 2, 4, 5, 3, 6, 2],
        [3, 9, 8, 4, 7, 3, 9, 8, 4, 7],
        [7, 3, 4, 5, 2, 7, 3, 4, 5, 2],
        [2, 3, 4, 6, 5, 2, 3, 4, 6, 5]])

In [ ]:
# 22. Normalize a 5x5 random matrix (★☆☆) hint: (x -mean)/std
a = np.random.random((5, 5))
c = np.mat(a)
c.mean()

0.5980693158925424

In [ ]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
a = np.dtype([("r", np.ubyte, 1),
              ("g", np.ubyte, 1),
              ("b", np.ubyte, 1),
              ("a", np.ubyte, 1)])
a

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [ ]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
a = np.mat([[2, 3, 4], [3, 5, 6], [6, 2, 3], [4, 2, 5], [5, 3, 2]])
b = np.mat([[4, 5], [2, 3], [3, 4]])
c = np.dot(a, b)
c

matrix([[26, 35],
        [40, 54],
        [37, 48],
        [35, 46],
        [32, 42]])

In [ ]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
a = np.arange(11)
a[(a >= 3) & (a <= 8)] *=-1
a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

In [ ]:
# 26. What is the output of the following script? (★☆☆)
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
# 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z = np.arange(3)
a = Z**Z
print(f"{a}\n")
b = 2 << Z >> 2
print(f"{b}\n")
c = Z <- Z
print(f"{c}\n")
d = 1j*Z
print(f"{d}\n")
e = Z/1/1
print(e)
# Z<Z>Z #ValueError

[1 1 4]

[0 1 2]

[False False False]

[0.+0.j 0.+1.j 0.+2.j]

[0. 1. 2.]


In [ ]:
# 28. What are the result of the following expressions? (★☆☆)
a = np.array(0) / np.array(0)
print(a)
b = np.array(0) // np.array(0)
print(b)
c = np.array([np.nan]).astype(int).astype(float)
print(c)

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  after removing the cwd from sys.path.


In [ ]:
# 29. How to round away from zero a float array? (★☆☆)
a = np.array([23.35, 8.49])
b = np.round(a, decimals = 1)
b

array([23.4,  8.5])

In [ ]:
# 30. How to find common values between two arrays? (★☆☆)
a = np.array([2, 3])
b = np.array([4, 2])
c = np.intersect1d(a, b)
c

array([2])

In [ ]:
# 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
a = np.ones(1) / 0
np.seterr(all="ignore")
a

array([inf])

In [ ]:
# 32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [ ]:
# 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
today = np.datetime64("today", "D")
print(f"Today - {today}")
yesterday = np.datetime64("today", "D") - np.timedelta64(1, "D")
print(f"Yesterday - {yesterday}")
tomorrow = np.datetime64("today", "D") + np.timedelta64(1, "D")
print(f"Tomorrow - {tomorrow}")

Today - 2022-10-02
Yesterday - 2022-10-01
Tomorrow - 2022-10-03


In [ ]:
# 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
july = ("July, 2016")
print(np.arange("2016-07", "2016-08",  dtype="datetime64[D]"))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
a = np.ones(3) * 1
b = np.ones(3) * 2
np.add(a,b,out=b)

np.divide(a,2,out=a)

np.negative(a,out=a)

np.multiply(a,a,out=a)

array([0.25, 0.25, 0.25])

In [ ]:
# 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
s = np.random.uniform(0, 10, 10)

first_method = s - s % 1
print(first_method)

second_method = np.floor(s)
print(second_method)

third_method = s.astype(int)
print(third_method)

fourth_method = np.trunc(s)
print(fourth_method)

[7. 9. 4. 8. 6. 6. 6. 1. 6. 8.]
[7. 9. 4. 8. 6. 6. 6. 1. 6. 8.]
[7 9 4 8 6 6 6 1 6 8]
[7. 9. 4. 8. 6. 6. 6. 1. 6. 8.]


In [ ]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
a = np.zeros((5, 5))
print(f"{a}\n")
a += np.arange(5)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
# 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
def generate():
  for i in range(15):
    yield i
a = np.fromiter(generate(), dtype = "float", count=-1)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


In [ ]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
a = np.linspace(0, 1, 12, endpoint = False) [1:] 
a

array([0.08333333, 0.16666667, 0.25      , 0.33333333, 0.41666667,
       0.5       , 0.58333333, 0.66666667, 0.75      , 0.83333333,
       0.91666667])

In [ ]:
# 40. Create a random vector of size 10 and sort it (★★☆)
a = random.random(10)
b = np.sort(a)
b

array([0.07955173, 0.16113106, 0.20662899, 0.21561187, 0.42540187,
       0.47352903, 0.51945783, 0.79990618, 0.81398826, 0.8491441 ])

In [ ]:
# 41. How to sum a small array faster than np.sum? (★★☆)
a = np.array([2, 3, 4, 5])
b = np.add.reduce(a)
b

14

In [ ]:
# 42. Consider two random array A and B, check if they are equal (★★☆)
a = np.random.randint(1, 2, 5)
b = np.random.randint(1, 2, 5)
c = np.allclose(a, b)
print(c)
d = np.array_equal(a, b)
print(d)

True
True


In [ ]:
# 43. Make an array immutable (read-only) (★★☆)
a = np.array([2, 3, 4])
b = a.flags.writeable
b

True

In [ ]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
a = np.random.random((10, 2))
b, c = a[:, 0], a[:, 1]
d = np.sqrt(b**2, c**2)
print(d)
e = np.arctan2(b, c)
print(e)

[0.79834042 0.53752353 0.46911527 0.50824584 0.33809813 0.63745424
 0.12681228 0.54261796 0.59251731 0.48999944]
[0.94290608 0.57274958 1.20206638 1.5691581  1.53555797 0.66044511
 0.55197246 1.37360695 0.64684128 1.42384617]


In [ ]:
# 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
a = random.random((10))
print(max(a))
b = a[a.argmax()] = 0
print(b)

0.7967831737145343
0


In [20]:
# 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
a = np.zeros((5, 5), [("x", float), ("y", float)])
a["x"], a["y"] = np.meshgrid(np.linspace(0, 1, 5)), np.linspace(0, 1, 5)
print(a)

[[(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]]


In [4]:
# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
x = np.arange(10)
y = x + 0.5
a = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(a))

33961.93294480236


In [12]:
# 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
for i in [np.int8, np.int16, np.int32, np.int64]:
  print(np.iinfo(i))
for j in [np.float32, np.float64]:
  print(np.finfo(j))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minex

In [18]:
# 49. How to print all the values of an array? (★★☆)
a = np.arange(20)
b = np.set_printoptions(threshold=np.inf)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [30]:
# 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
a = np.arange(50)
b = np.random.uniform(0, 50)
c = (np.abs(a-b)).argmin()
print(a[c])

16
